name: 新增健康证
description: 录入信息以生成新的健康证
labels: ["健康证"]
body:
  - type: dropdown
    id: gender
    attributes:
      label: 性别
      options:
        - 男
        - 女
    validations:
      required: true
  - type: input
    id: id_number
    attributes:
      label: 身份证号码
      placeholder: 请输入18位身份证号
    validations:
      required: true
  - type: input
    id: exam_date
    attributes:
      label: 体检日期
      placeholder: 例如 2026年7月15日 (有效期一年)
      default: 2026年7月15日 (有效期一年)
    validations:
      required: true
  - type: textarea
    id: body
    attributes:
      label: 备注信息（可选）
      description: 其他需要补充的信息
